
GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/5ec3b246e046b46fd04b6426


###
POST http://localhost:3000/subscribers/
Content-Type: application/json

{
    "name": "SAI",
    "subscribedToChannel": "WDS"
}


###
PATCH http://localhost:3000/subscribers/5ec3b246e046b46fd04b6426
Content-Type: application/json


{
    "name": "SAI CHARAN",
    "subscribedToChannel": "Web Dev Simplified"
}


###
DELETE http://localhost:3000/subscribers/5ec3b246e046b46fd04b6426

