
GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/5e775fe369712747e8889b4e


###
POST http://localhost:3000/subscribers/
Content-Type: application/json

{
    "name": "SAI",
    "subscribedToChannel": "WDS"
}


###
PATCH http://localhost:3000/subscribers/5e775fe369712747e8889b4e
Content-Type: application/json


{
    "name": "SAI CHARAN",
    "subscribedToChannel": "Web Dev Simplified"
}


###
DELETE http://localhost:3000/subscribers/5e775fe369712747e8889b4e

